version: "3.9"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.9
    container_name: kafka
    volumes:
      - kafka_data:/bitnami
    networks:
        - linkedin-network
    environment:
      # Kraft configuration
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093 #Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  kafbat-ui:
    container_name: kafbat-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8090:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_KSQLDBSERVER: http://ksqldb0:8088


  notification-db:
    image: postgres
    container_name: notification-db
    environment:
      - POSTGRES_DB=notificationDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - linkedin-network
    ports:
      - "5432:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  post-db:
    image: postgres
    container_name: posts-db
    environment:
      - POSTGRES_DB=postDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - linkedin-network
    volumes:
      - post-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_DB=userDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - linkedin-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  connection-db:
    image: neo4j
    container_name: connection-db
    environment:
        - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - connections-db-data:/data
    networks:
        - linkedin-network

  discovery-server:
    image: meet16123/linkedin-app:discovery-server
    container_name: discovery-server
    networks:
      - linkedin-network
    ports:
      - "8761:8761"

  posts-service:
    image: meet16123/linkedin-app:posts-service
    container_name: posts-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - post-db
      - kafka

  user-service:
    image: meet16123/linkedin-app:user-service
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - user-db
      - kafka

  notification-service:
    image: meet16123/linkedin-app:notification-service
    container_name: notification-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - notification-db
      - kafka

  connections-service:
    image: meet16123/linkedin-app:connections-service
    container_name: connections-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - connection-db
      - kafka

  api-gateway:
    image: meet16123/linkedin-app:api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - linkedin-network
    depends_on:
      - discovery-server

networks:
  linkedin-network:


volumes:
  kafka_data:
  notification-db-data:
  post-db-data:
  user-db-data:
  connections-db-data:
